on:
  push:
    branches:
      - "main"

name: Publish

jobs:
  test-linux:
    name: "Test (Linux)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --release
      
  test-windows:
    name: "Test (Windows)"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --release

  publish:
    name: "Publish"
    needs:
      - test-linux
      - test-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --verbose --token ${{ secrets.CRATES_IO_API_TOKEN }}

      
    
  
